export const errors = {
  BAG_DOES_NOT_EXIST: "BAG_DOES_NOT_EXIST",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  INVALID_ENVIRONMENT: "INVALID_ENVIRONMENT",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  INVALID_API_KEY: "INVALID_API_KEY",
  INVALID_REQUEST: "INVALID_REQUEST",
  FLAG_NOT_FOUND: "FLAG_NOT_FOUND",
  COULDNT_UPDATE_FLAG: "COULDNT_UPDATE_FLAG",
  FLAG_ALREADY_EXISTS: "FLAG_ALREADY_EXISTS",
};
